### ISSUE TITLE
app:cardBackgroundColor 不可以引用 drawable 资源文件

### ISSUE THREAD

**Issue by believe666a** [meetsl/SCardView-master#13]
想用 shape  完成一个渐变颜色，无法完成，希望能增加。谢谢。

**Comment by believe666a** [comment]
换了一张方式实现，SCardView 调成透明背景，
![image](https://user-images.githubusercontent.com/37438988/65008985-bede8f80-d93d-11e9-977e-c5e4ae862a7d.png)

**Comment by meetsl** [comment]
谢谢
