### ISSUE TITLE
升级1.2 会提示错误

### ISSUE THREAD

**Issue by believe666a** [meetsl/SCardView-master#14]
![image](https://user-images.githubusercontent.com/37438988/65008705-d0736780-d93c-11e9-9e93-14db8c693854.png)
![image](https://user-images.githubusercontent.com/37438988/65008825-2fd17780-d93d-11e9-958f-0e0d04d6664b.png)

根据提示加入 tools:replace="android:appComponentFactory
还是会提示 
![image](https://user-images.githubusercontent.com/37438988/65008876-5d1e2580-d93d-11e9-8690-cac25d710bff.png)

**Comment by meetsl** [comment]
建议先将应用 迁移到 AndroidX，后续会查看并解决这个问题
