### ISSUE TITLE
能否做到只显示一边的阴影

### ISSUE THREAD

**Issue by LLQQHH** [meetsl/SCardView-master#22]

**Comment by meetsl** [comment]
https://camo.githubusercontent.com/812584f605ff63e1c580c0cb232c50eb4db52930829d44f72f3b26d7512b88df/68747470733a2f2f696d67323031382e636e626c6f67732e636f6d2f626c6f672f3730393539342f3230313831302f3730393539342d32303138313030393130323032383230362d313531363236303131342e706e67 
readme 示例图，不是你想要的效果吗

**Comment by LLQQHH** [comment]
不是啊，你这个要吗不显示，如果显示至少是两边阴影，我说的是只需要一边阴影，如
![QQ截图20201116101232](https://user-images.githubusercontent.com/19651932/99205710-48b11380-27f4-11eb-9061-a9ff39e8a417.png)

**Comment by meetsl** [comment]
https://camo.githubusercontent.com/f31e666d92ca0e5ae5af9037c06185341b10553df8e0b015970461b1ad1c8d4f/68747470733a2f2f696d67323031382e636e626c6f67732e636f6d2f626c6f672f3730393539342f3230313830392f3730393539342d32303138303931363135303632383835352d313432313433333133322e706e67
这个是目前支持的所有阴影，如果达不到你要的效果。那就是目前不支持。你发的这个图片，阴影是在下方，两边布满屏幕。如果是这个效果，现在应该是支持的。

**Comment by LLQQHH** [comment]
阴影是在下方，两边布满屏幕，发现用你的是不行的，即使我设置为match_parent，两边还是会多出一些间隙出来

**Comment by meetsl** [comment]
好的，那满足不了你的需求。你可以看下这篇文章，了解一下阴影的其他实现方案。https://www.cnblogs.com/aimqqroad-13/p/9648280.html

**Comment by LLQQHH** [comment]
好吧，那谢谢，还有有一个疑问，就是光源在LT的时候，这个时候阴影是在右下两面，左上是没有阴影的，为啥这个时候左上还是有空白的间距，这是故意这么做的，还是因为技术原因不好去除空白
