### ISSUE TITLE
请问内容区域能不能铺满cardview

### ISSUE THREAD

**Issue by tanzhihao1qaz** [meetsl/SCardView-master#4]
![image](https://user-images.githubusercontent.com/28348014/52797857-b7a68900-30b1-11e9-8b68-33e958c5dc6a.png)
就如图，就算设为0，红色部分都不能铺满，还是看到一点背景的蓝绿色

**Comment by meetsl** [comment]
你好，边角不会对内容进行裁剪，为了显示圆角，限制示内容区域不能铺满
