### ISSUE TITLE
SCardView包裹10个条目的RecyclerView时，数据展示有问题

### ISSUE THREAD

**Issue by wisdomcai** [meetsl/SCardView-master#9]
第一次设置数据item显示特别小，再设置一次数据就正常了，期待共同解决该问题

**Comment by meetsl** [comment]
能具体说明一下你的显示情况么，有效果图么，以及系统信息，请发我邮箱meetsl.dev@gmail.com。期待你的回馈

**Comment by meetsl** [comment]
时间长了，如有问题请另行讨论
